config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :builders
  resources :proyects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "proyects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/builder.rb
class Builder < ApplicationRecord
  belongs_to :proyect
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :proyect

end

app/models/proyect.rb
class Proyect < ApplicationRecord
    has_many :builders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/builders_controller.rb
class BuildersController < ApplicationController
  before_action :set_builder, only: %i[ show edit update destroy ]

  # GET /builders or /builders.json
  def index
    @builders = Builder.all
    @proyects = Proyect.all
  end

  # GET /builders/1 or /builders/1.json
  def show
  end

  # GET /builders/new
  def new
    @builder = Builder.new
    @proyect = Proyect.all
  end

  # GET /builders/1/edit
  def edit
  end

  # POST /builders or /builders.json
  def create
    @builder = Builder.new(builder_params)

    respond_to do |format|
      if @builder.save
        format.html { redirect_to builder_url(@builder), notice: "Builder was successfully created." }
        format.json { render :show, status: :created, location: @builder }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builders/1 or /builders/1.json
  def update
    respond_to do |format|
      if @builder.update(builder_params)
        format.html { redirect_to builder_url(@builder), notice: "Builder was successfully updated." }
        format.json { render :show, status: :ok, location: @builder }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builders/1 or /builders/1.json
  def destroy
    @builder.destroy

    respond_to do |format|
      format.html { redirect_to builders_url, notice: "Builder was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_builder
      @builder = Builder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def builder_params
      params.require(:builder).permit(:name, :proyect_id, :email)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:card, :number, :expiration, :monto, :proyect_id)
    end
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :set_proyect, only: %i[ show edit update destroy ]

  # GET /proyects or /proyects.json
  def index
    @proyects = Proyect.all
  end

  # GET /proyects/1 or /proyects/1.json
  def show
  end

  # GET /proyects/new
  def new
    @proyect = Proyect.new
  end

  # GET /proyects/1/edit
  def edit
  end

  # POST /proyects or /proyects.json
  def create
    @proyect = Proyect.new(proyect_params)

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to proyect_url(@proyect), notice: "Proyect was successfully created." }
        format.json { render :show, status: :created, location: @proyect }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyects/1 or /proyects/1.json
  def update
    respond_to do |format|
      if @proyect.update(proyect_params)
        format.html { redirect_to proyect_url(@proyect), notice: "Proyect was successfully updated." }
        format.json { render :show, status: :ok, location: @proyect }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1 or /proyects/1.json
  def destroy
    @proyect.destroy

    respond_to do |format|
      format.html { redirect_to proyects_url, notice: "Proyect was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proyect_params
      params.require(:proyect).permit(:name, :lastname, :rut, :email, :region, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builders_helper.rb
module BuildersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/builders/_builder.html.erb
<div id="<%= dom_id builder %>">
  <p>
    <strong>Name:</strong>
    <%= builder.name %>
  </p>

  <p>
    <strong>Proyect:</strong>
    <%= builder.proyect_id %>
  </p>

    <p>
    <strong>Proyect:</strong>
    <%= builder.proyect.email %>
  </p>

</div>

app/views/builders/_form.html.erb
<%= form_with(model: builder) do |form| %>
  <% if builder.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(builder.errors.count, "error") %> prohibited this builder from being saved:</h2>

      <ul>
        <% builder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :proyect_id, style: "display: block" %>
    <%= form.text_field :proyect_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/builders/edit.html.erb
<h1>Editing builder</h1>

<%= render "form", builder: @builder %>

<br>

<div>
  <%= link_to "Show this builder", @builder %> |
  <%= link_to "Back to builders", builders_path %>
</div>

app/views/builders/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col">
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col text-center">
      <h1>Bienvenido a la Zona Constructor</h1>
    </div>
  </div>

  <div class="card my-3 mx-5">
    <div class="row g-0">
      <div class="col-md-4">
        <%= image_tag "logo-fixer", class:"logo-body" %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Quieres ser parte de este Equipo?</h5>
          <p class="card-text">Solo registrate como Constructor y ya estarás siendo parte de nuestro equipo y recibiendo proyectos para cotizar. Así de fácil!!!</p>
          <button type="button" class="btn btn-dark btn-lg">Registrarme</button>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="proyects">
    <table class="table table-hover mt-5">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Nombre</th>
          <th scope="col">Apellido</th>
          <th scope="col">Región</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
      <% @proyects.each do |proyect| %>
        <tr>
        
            <td><%= proyect.id %></td>
            <td><%= proyect.name %></td>
            <td><%= proyect.lastname %></td>
            <td><%= proyect.region %></td>
            <td><%= link_to "Contactar", new_builder_path(@proyect) %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div> 

    <!-- <div id="builders">
        <% @builders.each do |builder| %>
          <%= render builder %>
          <p>
            <%= link_to "Show this builder", builder %>
          </p>
        <% end %>
      </div>
      <%= link_to "New builder", new_builder_path %>
    -->

app/views/builders/new.html.erb
<h1>Nueva cotización</h1>
<%= render "form", builder: @builder %>
<br>
<div>
  <%= link_to "Back to builders", builders_path %>
</div>

app/views/builders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @builder %>

<div>
  <button type="button" class="btn btn-dark">
    <%= link_to "Volver a Zona Constructores", builders_path %>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fixer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">FIXER</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Home", proyects_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Ingresar Proyecto", new_proyect_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Zona de Constructores", builders_path, class:"nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-5 m-0 ">
    <img src="https://i.pinimg.com/originals/b6/3b/54/b63b54d4f0074710e9dd0f8e6d3c9fbd.jpg" style="width: 100px; height: 30px;">
    <select name="card" action="get" class="form-select p-0 ms-auto me-auto mt-2" aria-label="Default select example" style="width: 200px">
      <option selected>Seleccione su tarjeta</option>
      <option value="1">Visa</option>
      <option value="2">Master</option>
    </select>
  </div>

  <div>
    <%= form.label :number, style: "display: block", class:"mt-2" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :expiration, style: "display: block", class:"mt-2"  %>
    <%= form.text_field :expiration %>
    <p>Formato fecha dd/mm/aa </p>
  </div>

  <div>
    <%= form.label :monto, style: "display: block", class:"mt-2"  %>
    <%= form.label :$6500 %>
  </div>

  <div>
    <%= form.label :proyect_id, style: "display: block", class:"mt-2"  %>
    <%= form.text_field :proyect_id, class:"mb-4" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Card:</strong>
    <%= payment.card %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= payment.number %>
  </p>

  <p>
    <strong>Expiration:</strong>
    <%= payment.expiration %>
  </p>

  <p>
    <strong>Monto:</strong>
    <%= payment.monto %>
  </p>

  <p>
    <strong>Proyect:</strong>
    <%= payment.proyect_id %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-4 ms-auto me-auto my-5">
      <div class="card" style="width: 24rem; height: 33rem">
        <div class="card-body">
        <h1>Ingresa tu forma de pago</h1>
          <%= render "form", payment: @payment %>
          <br>
        <div>
      </div>
    </div>
  </div>
</div>


  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
<button type="button" class="btn btn-dark">
  <%= link_to "Volver al Home", proyects_path, class:"nav-link" %>
</button>
  
</div>

app/views/proyects/_form.html.erb
<%= form_with(model: proyect) do |form| %>
  <% if proyect.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(proyect.errors.count, "error") %> prohibited this proyect from being saved:</h2>

      <ul>
        <% proyect.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-2">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="my-2">
    <%= form.label :lastname, style: "display: block" %>
    <%= form.text_field :lastname %>
  </div>

  <div class="my-2">
    <%= form.label :rut, style: "display: block" %>
    <%= form.text_field :rut %>
  </div>

  <div class="my-2">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class="my-2">
    <%= form.label :region, style: "display: block" %>
    <%= form.text_field :region %>
  </div>

  <div class="my-2">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/proyects/_proyect.html.erb
<div id="<%= dom_id proyect %>">
  <th>    
    <%= proyect.id %>
    <span style="color: red;">Recuerde este ID, lo necesitará para pagar</span>
  </th>
  <td><%= proyect.name %></td>
  <td><%= proyect.lastname %></td>
  <td><%= proyect.rut %></td>
  <td><%= proyect.email %></td>
  <td><%= proyect.region %></td>
  <td><%= proyect.description %></td>
</div>

app/views/proyects/edit.html.erb
<h1>Editing proyect</h1>

<%= render "form", proyect: @proyect %>

<br>

<div>
  <%= link_to "Show this proyect", @proyect %> |
  <%= link_to "Back to proyects", proyects_path %>
</div>

app/views/proyects/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="ideas" class="row">
  <div class="col-2">
    <a class="foto-ideas" href="#">
      <img src="https://www.hola.com/imagenes/decoracion/20210215184361/cocinas-modernas-integrar-madera-mc/0-919-885/madera-cocina-m.jpg" alt="" width="200" height="200">
    </a>
  </div>
  <div class="col-2">
    <a class="foto-ideas" href="#">
      <img src="https://www.hola.com/imagenes/decoracion/20200424166556/orden-casa-accesorios-cocina-mejor-organizada-mc/0-815-882/accesorios-cocina-orden-m.jpg" alt="" width="200" height="200">
    </a>
  </div>
  <div class="col-2">
    <a class="foto-ideas" href="#">
      <img src="https://sc02.alicdn.com/kf/HTB1xrBxXUrrK1RkSne1q6ArVVXaa/202757231/HTB1xrBxXUrrK1RkSne1q6ArVVXaa.jpg_.webp" alt="" width="200" height="200">
    </a>
  </div>
  <div class="col-2">
    <a class="foto-ideas" href="#">
      <img src="https://hips.hearstapps.com/es.h-cdn.co/mcres/images/mi-casa/cocinas/cocinas-con-office/cocina-blanca-con-encimera-de-madera/1134668-1-esl-ES/cocina-blanca-con-encimera-de-madera.jpg?crop=0.731xw:0.974xh;0.123xw,0.0171xh&resize=640:*" alt="" width="200" height="200">
    </a>
  </div>
  <div class="col-2">
    <a class="foto-ideas" href="#">
      <img src="https://images.hola.com/imagenes/decoracion/20200217160191/decoracion-cocinas-imprescindibles-cocina-moderna/0-780-736/cocina-moderna-7t-t.jpg" alt="" width="200" height="200">
    </a>
  </div>
  <div class="col-2">
    <a class="foto-ideas" href="#">
      <img src="https://discesur.es/wp-content/uploads/2020/10/25052020-SANTOS-GRIS-VISION-SEDA-1030x774.jpg" alt="" width="200" height="200">
    </a>
  </div>
</div>
<div class="row my-3 marcas"></div>
  <div class="col-4 d-inline-block marcas" style="width: 18rem;">
    <h3>Publicidad</h3>
  </div>
  <div class="col-4 d-inline-block marcas" style="width: 18rem;">
    <h3>Publicidad</h3>
  </div>
  <div class="col-4 d-inline-block marcas" style="width: 18rem;">
    <h3>Publicidad</h3>
  </div>
</div>


<div class="card my-3 mx-5">
  <div class="row g-0">
    <div class="col-md-4">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Alguna idea en mente?</h5>
        <p class="card-text">Ingresa tu proyecto y obtén cotizaciones de profesionales serios.</p>
        <br>
        <button type="button" class="btn btn-dark btn-lg"><%= link_to "Ingresar proyecto", new_proyect_path %></button>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-3">
      <div class="card" style="width: 18rem;; height: 24rem">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZQCdKYEOxfHkjWstsbPcl655wyARzanUGkA&usqp=CAU" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    </div>
    <div class="col-3">
      <div class="card" style="width: 18rem;; height: 24rem">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6v-6xQJ7LFnn53MrRIOqUItZNeCMw_MyhOWB4JU1xJ75LSXLl4wFc5dZ0aNUVpGw38Vw&usqp=CAU" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    </div>
    <div class="col-3">
      <div class="card" style="width: 18rem; height: 24rem">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxxM6DizIlmN8m4mKcQ7aPMFgwxVhLou1tug&usqp=CAU" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    </div>
    <div class="col-3">
      <div class="card" style="width: 18rem;; height: 24rem">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmbwmhiS61kRI9zR7PanQDO6IHTHbaeWutZw&usqp=CAU" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/proyects/new.html.erb
<div class="container">
  <div class="row text-center ms-auto me-auto">
    <div class="col-4 ms-auto me-auto my-5">
      <div class="card" style="width: 24rem; height: 33rem">
        <div class="card-body">
          <h1>Mi proyecto</h1>
          <%= render "form", proyect: @proyect %>
          <br>
          <div>
            <%= link_to "Back to proyects", proyects_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/proyects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @proyect %>

<div>
  <%= link_to "Show this proyect", proyect %>
  <%= link_to "Edit this proyect", edit_proyect_path(@proyect) %> |
  <%= link_to "Pagar", new_payment_path(@proyect[:id]) %>

  <%= button_to "Destroy this proyect", @proyect, method: :delete %>
</div>